### ISSUE TITLE
gatsby and goober

### ISSUE THREAD

**Issue by cusxio** [cristianbote/goober#161]
## Current Behaviour

`glob` styles are not applied to sub pages in `gatsby`, i.e. pages other than `/`.

#### Reproduction

https://github.com/cusxio/goober-test

1. Run `yarn build`
2. See output in public folder. Global styles are only applied to `/`, and not `/two`.

## Side note 

A missing semi-colon in `glob` will also cause the styles to not be rendered.

#### Reproduction

https://github.com/cusxio/goober-test/blob/master/src/wrapPageElement.js#L7

1. Remove the semi-colon on the line above.
2. Run `yarn build`, and the styles will not be rendered in the output `html`.

## Potentially related
#105

**Comment by cristianbote** [comment]
Hey @cusxio thank you so much for opening this issue.

Indeed, this is awkward -- and I should address this inside README. What's happening here is that `glob` is actually a `css` call with the global flag `{ g: 1 }` that returns an empty string. There are a couple things that you could do and depends on what you prefer:

1. Move the `glob` call inside `wrapPageElement`.

Basically instead of calling `glob` outside the function, should be called for each wrapped element. There are no perf impacts, or really minimal, since goober uses two cache layers (memoizations), for input and outputs.

2. Create a `Glob` jsx component.

```jsx
export const Glob = () => glob`
  body {
    color: orange;
  }
`;
```

And then you could use it as part of your hierarchy. `glob` returns an empty string so I wouldn't worry about messing up any layouts.

Let me know what works best for you.

Oh and about the semicolon missing error, that's due to the regex parser rule that `goober` uses. Do you feel like that's something important for users? I am really biased and I have no objective opinion on it, I always use `;` everywhere in my css and I have no clue if people are defining css without the needed `;`.

**Comment by cusxio** [comment]
Thank you for the prompt reply! Appreciate it. 🙏🏻

I think Option 1 works.

Option 2 will inflict a TypeScript error as [void](https://github.com/cristianbote/goober/blob/1cf548838e3f6e4919a547875d45fa1f61c241c5/goober.d.ts#L31) is not a valid JSX element.

So you would need something like 

```js
export const Glob = () => {
 glob`
  body {
    color: orange;
  }
`;
return null;
}
```

which is essentially Option 1.

---

> Oh and about the semicolon missing error, that's due to the regex parser rule that goober uses. Do you feel like that's something important for users? I am really biased and I have no objective opinion on it, I always use ; everywhere in my css and I have no clue if people are defining css without the needed ;.

Technically, omitting the semicolon for the last line of the CSS is [valid CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax). So I would expect some users to expect it to work.

I too don't really have an opinion about this, because `prettier` can usually auto-correct it in `css` template literals. However, since `glob` isn't supported by prettier, it doesn't auto-correct. That's how I bump into this issue!

**Comment by cristianbote** [comment]
Awesome! Glad that works for you.

> since glob isn't supported by prettier

Umm, woot? 😞  that's news to me. Is it the type definition at wrong here? 🤔

**Comment by cusxio** [comment]
Not sure if we are on the same page, but here's an example.

[Example](
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAhgVxhAWgDMIAnAWyxgGcAabAEweo2rnIEtIAbaAHShhq1AAYCARljABrAOakIOKAwzABPMkgyk4DAQF8BIgNwCB6DAwhwWUCDAAWHKLIGze4sVEkz5i5arqELykWjp6UIZQJmZQILQgEAAOMBzQ1MigWKQKAO4ACtkIGShYAG4QHAzxIOKkUtJwMADKSVLOssgwpDhwCQ4w5NwA6k7w1G1gcM3FHKllcwCeyODCNc5spDD59bKUyERY3GwJAFbUAB4AQvUyTc1Y5HAAMs5wB0cnIOcXzR3ccAAijh7O8kIdjn0QG1SJsVpJxHBuDUkqRnDBhlVHMgABwABgSqIgbGG9SSK1RNjgpDK7wSAEcQfAdskSiAsNQCFA4LpdDUdIyODodlg9lgPpCEmxOF0elDqP8gUywRCvjAsOJMQxsUgAEwJbpYDjcDoAYQg5H2KDs3JqODYABUNSVVVCyr0AJLKBAtMBolIAQWUzRgiwBErY+n0QA).

Notice the output on the right. One is corrected, one stays the same. So for `glob`, it doesn't get auto correct.

I don't think it has anything to do with the type definitions, but more with how prettier works. So `goober` not supporting optional semicolon is a "gotcha" in _this sense_, but it's not a deal breaker! Thank you for this awesome library!
