### ISSUE TITLE
Props are not typed with Preact

### ISSUE THREAD

**Issue by kocsis1david** [cristianbote/goober#175]
TypeScript cannot find `JSX` when goober is used with preact:

![image](https://user-images.githubusercontent.com/722066/89188539-19f19300-d59f-11ea-9aab-189eb60f3464.png)

The code still compiles and works, but if you hover over `props.primary` in VSCode, it will show that the type is `any`.

~~~ts
const Button = styled("button") <{ primary: boolean }>`
    background: ${props => props.primary ? "orange" : "white"};
    color: ${props => props.primary ? "white" : "orange"};
`;
~~~

**Comment by kocsis1david** [comment]
Placing `import JSX = preact.JSX;` into a `.d.ts` file seems to fix the problem, but it would be nice if it were working fine after install.

**Comment by cristianbote** [comment]
Hey @kocsis1david, thanks for opening this issue, much appreciate it!

Yeah 😬  this feels like something that it's out of my understandings -- really noob when it comes of TypeScript. All of the typings are community contributions so I have to ask the community to help out on this one. Or if you feel that you know how to do it, feel free to open up a PR. More than welcome!

**Comment by ryansolid** [comment]
Yeah Preact behaves itself and doesn't invade the global namespace like some inconsiderate frameworks... cough.. I was working on trying to follow suit with Solid and was able to get everything but this to work. This is a hard problem though since goober can't know which JSX it's dealing with so it can't import. App developers can move Preact types to global but that is a shame. My TS is no better so I have no ideas. For now I'm going to hand create the types myself for my library.
