### ISSUE TITLE
head style embed [optimizations]

### ISSUE THREAD

**Issue by maxval1** [cristianbote/goober#196]
Hi, 
I have a situation and i don't know how resolve that's optimization see [demo](https://jmp.sh/BP9egbH) live [codesandbox](https://codesandbox.io/s/flamboyant-heisenberg-i5fh3?file=/src/App.tsx).
My question is it possible to generate one class an changed the properties for this class, or paste one class default with some properties and if have some new value added another class with that's changed.
Thanks!!

**Comment by cristianbote** [comment]
Hey @maxval1, thank you so much for opening this issue. Really appreciate it.

Indeed, that's a tricky one. So what happens in here is that for each step the component gets re-rendered due to state changes. That means, each re-render, goober, is re-creating those classes. So, based on the linked codesandbox and your description, I assuming that you want to have a className? Is that it? If that's the case, you could either define one by hand using the `className` prop:
```jsx
<Button size={size} className="button">Button</Button>
```

So now the rendered output will be:
```html
<button class="go2621302557 button" size="51">Button</button>
```

But maybe this is not what you're trying to achieve? 😅  If it's not please let me know.

**Comment by maxval1** [comment]
Hi @cristianbote, so my problem is when I change some properties like size 12 -> 13 right now it is generating all properties in a new css class and appends it in head, so if I had 20 properties for example:
```css
font-size: 12px;
color: red;
background: blue;
line-height: 1.1;
/* more properties */
```
and I change only `font-size: 13px;` then it generates a new classes and appends this big css in head
```css
font-size: 13px; /* changed */
color: red;
background: blue;
line-height: 1.1;
/* more properties */
```
maybe we need to change the font-size in old class to avoid generating a new css class

**Comment by cristianbote** [comment]
Oh, now I get it! 😄 

Yup, true, goober will generate that, so there's one thing that you could do to minimise the amount of work, and that is https://github.com/cristianbote/goober#extending. Bottom line, you can create a `Base` component that would hold the properties that are not gonna change and then, extend the `Button` with that `Base` and define the changing properties. I know it's a bit more work to handle this, but you can achieve the optimisation you are looking for.

In the past I did tried to look into separating the dynamic from static parts from the tagged template, but I would end-up over the size threshold 😄 . But still looking into a way to achieve it nicely.

Let me know if extending works for you.

**Comment by maxval1** [comment]
Partial works
Thanks!!
