### ISSUE TITLE
Is it possible to trim className?

### ISSUE THREAD

**Issue by winston0410** [cristianbote/goober#213]
I would like to reduce the payload by minifying the className of the attached <style> from goober, is there any option for me to do that?

**Comment by cristianbote** [comment]
Hey @winston0410, thanks for opening this issue.

I don't believe there's a way to do that within goober. May I ask what exactly you are trying to achieve? Is the length of the className to be shorter? The `toHash` function handles generating the class hash. At first it used a `.toString(36)` but that took byte space and removed it.

So, my main question to you is, what exactly you are looking for to achieve?

**Comment by winston0410** [comment]
@cristianbote Thank you so much for your quick response. I think I have asked my question incorrectly. I want to trim the className for the elements instead of `<style>`, like this:

Before:
```
<p class="go2153847280">Hello world</p>
```
After:
```
<p class="as2">Hello world</p>
```

The reason for doing this is to reduce the size of html and css stylesheet. I think this is a feature missing in goober?

**Comment by cristianbote** [comment]
Oh, I see now.

The generated classNames are not _random_, each className is generated depending on the contents of the rule. Let's look at an example.

Say you have this styled component:
```jsx
import { styled } from 'goober';

const Wrapper = styled('div')`
  border: 0;
  padding: 2em;
`;
```

The className generated by goober, in this case, represents the _encoded_ value of the CSS properties we have defined. The following css will get appended:

```css
.go1826659220 {
  border: 0;
  padding: 2em;
}
```

So, if you would want to _trim_ the className you would have to make sure that the trimmed className is unique to that CSS declaration. But I am certain that this is how each and every css-in-js library works inside.

Have you ran into size issues because of the length of the classNames? Can you share the findings?

**Comment by winston0410** [comment]
Thank you so much for your reply. I think that size doesn't matter much in the end, but as a developer who wants to optimize to the very end, I think this is needed. For website like Google or Medium, they have minimized their CSS className as well while keeping it unique.

One question though, why goober use number instead of any hash for generating unique CSS name? Is it because of bundle size issue? I am asking this because using hash would have more combinations in the same length of CSS name, thus we can trim it safely.

**Comment by cristianbote** [comment]
I think I am not explaining it well enough.

The classNames are already minimised.

The classNames are already a hash. Why numbers? Because that's the encoded result, without the `.toString(36)` call that would take a radix number to encode it with that base.

To reiterate over the above example, for the className `go1826659220` the hash is `1826659220`, the number part. If we would call `.toString(36)` on that number we would get `u7jn9w`. Is this what you are looking for? To have the className hashed with a radix?

**Comment by cristianbote** [comment]
If there's anything else that needs to be cleared out please reopen it. Thank you!
