### ISSUE TITLE
Documentation Site

### ISSUE THREAD

**Issue by vandreleal** [cristianbote/goober#221]
Hi @cristianbote,

Congratulations on creating goober! I've created a documentation website and would like to check if you like the idea of having a website for goober. The website was created using [Docusaurus 2](https://v2.docusaurus.io) and is currently hosted at https://gooberjs.github.io. I've also invited you to the organization `gooberjs` that I created for hosting additional resources in the future.

Thanks!

**Comment by cristianbote** [comment]
Wooow!

Thank you @vandreleal! Much appreciate the effort! Amazing! 👍  😃 

Do you think a new organisation for `gooberjs` would be a great fit? I've played around with the idea a while back as well, trying to consolidate the ecosystem, and it felt a bit odd to me.

My reasoning was that for documentation, like you've so amazingly generated the docs 🎉 , a `docs` folder in the main repo would do it. Then for the rest of packages, they could live under the `packages` folder due to tight integration between the main source. Which if they would be to be moved outside the main repo some sort of package alias orchestration should have to happen and I am not that good at it nor I want to spend time on it.

Also this relates to #112.

Would you be open to move the docs and pages into the main repo?

Thank you so much! Waw, I'm blown away by this. Amazing.

**Comment by vandreleal** [comment]
Happy to hear that, @cristianbote! 

Sure thing! I'll fork the repo and play a little with the deployment to see if having the docs as a folder in the main repo would affect the ability to use a GitHub workflow to handle deployments automatically. Get back to you soon!

**Comment by vandreleal** [comment]
Hi @cristianbote, I've just created the PR. The workflow `docs` takes care of deploying the site whenever there's a push to master. After the first successful run, you will need to go to https://github.com/cristianbote/goober/settings and set the GitHub Pages source to `gh-pages`. The website will be available at https://cristianbote.github.io/goober. I'll create a DocSearch key request at https://docsearch.algolia.com/apply after the website is published and update the Algolia section sometime this week.

**Comment by cristianbote** [comment]
Something is up with the way docusaurus has generated the website? 🤔  https://goober.js.org/ looks odd 😄

**Comment by cristianbote** [comment]
Maybe we could buikd it by hand with `wmr`+`goober` based on the root `Readme.md`?

**Comment by vandreleal** [comment]
That's odd., @cristianbote. Have you set the custom domain in the settings page to https://goober.js.org?

**Comment by vandreleal** [comment]
Hi @cristianbote, I've updated my fork with your latest changes including https://github.com/cristianbote/goober/commit/3c4804cf5a85c253a82fc399d081e545a1284e56, and set the custom domain as `goober.js.org` for testing. It seems to be working well now https://goober.js.org. Please let me know when you apply the change on your side and I'll remove the custom domain from my fork.

![goober](https://user-images.githubusercontent.com/9258892/103821774-a4a65480-504d-11eb-94f2-3004f47296b4.png)

**Comment by cristianbote** [comment]
![Screenshot 2021-01-07 at 00 06 37](https://user-images.githubusercontent.com/3405161/103824263-3f1d8c80-507c-11eb-960f-59b87ef1d809.png)

Did tried to do it earlier but it keeps displaying this error. 🤔  Is it because of your fork?

**Comment by vandreleal** [comment]
I think so. Just removed the custom domain from my fork. Can you please try again?

**Comment by cristianbote** [comment]
It still says that. Trying to unpublish and then publish again.

**Comment by cristianbote** [comment]
woohoo! That did it! @vandreleal! 👍  Thank you so much! 😄
