### ISSUE TITLE
Same web component added more than once

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/goober#23]
There's an issue where using the same web component twice would end-up not styled, but with the className generated.

**Comment by michael-klein** [comment]
Some more information: The problem is that right now, we basically have a single cache that we check to figure out if a style has already been added to the page. This means that if say, we have two instances of a web component on the page only the first would get their style tag populated, because the system thinks that the styles were already rendered for the second.

I have a solution to handle all of this in a much better manner - but the bundle size isn't there yet.
