### ISSUE TITLE
Using theme with Next.js

### ISSUE THREAD

**Issue by josiahwiebe** [cristianbote/goober#246]
I'm moving a project over from `styled-components` and everything has been going super smoothly so far!

I've just had some difficulty implementing theming. I used the convention in the [`useTheme`](https://goober.js.org/api/setup#with-theme) example, but the `props` don't even seem to be getting defined (I get a "cannot read property 'theme' of undefined" error). 

Here's a CodeSandbox example: https://codesandbox.io/s/runtime-browser-zeuw1

It's probably a silly error on my part, but I can't seem to figure it out! Any help would be appreciated.

**Comment by cristianbote** [comment]
Hey @josiahwiebe, let me look into this. Kinda strange indeed! I'll get back.

**Comment by cristianbote** [comment]
oooh! The error is coming from `createGlobalStyle` 😬  and I think know why.

So what's happening is that `styled` is govern by the `setup` method being called. That means, the `setups` only exists to determine the pragma that goober should use. The `css` api however knows nothing about `setup` since they are not tied at all. So one can use `css` without the need to call `setup`.

This is a limitation for sure and an oversight on my part. I'm gonna look into it to see if there's something I can do about it.

Thanks for opening this issue!

**Comment by cristianbote** [comment]
Hey @josiahwiebe with the recent PR this got fixed. Checkout your sandbox with the updated version https://codesandbox.io/s/eager-cherry-57c9u.

Will push a new version soon.

**Comment by josiahwiebe** [comment]
Looks great! Thanks so much 🙌

**Comment by jlalmes** [comment]
@cristianbote - Is it possible to add types so that we can use the `DefaultTheme` inside `createGlobalStyles`. Currently receiving `Parameter 'p' implicitly has an 'any' type.ts(7006)`.

```
const GlobalStyles = createGlobalStyles`
  ::selection {
    color: ${(p) => p.theme.color.white()};
    background-color: ${(p) => p.theme.color.primary(0.95)};
  }
 `
 ```
