### ISSUE TITLE
bundle has arrow function，not support ie11

### ISSUE THREAD

**Issue by huanqingli** [cristianbote/goober#258]

**Comment by cristianbote** [comment]
Hey @huanqingli indeed! I guess the https://github.com/cristianbote/goober#browser-support section should be updated reflecting it. Would you like to help out with that?

**Comment by eone666** [comment]
@cristianbote You need to configure the babel config

Enter the browsers you wish to support into the target property

**Comment by eone666** [comment]
```javascript

targets: {
                    "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
                }
```

**Comment by itsabdessalam** [comment]
I encountered the same issue recently and this is what I did.

If you are using webpack or another bundler, you can use babel in your project in order to support older browsers.
Be sure to specify the babel configuration (with necessary presets and plugins) in `babel.config.json` to also compile imported node_modules packages (see https://babeljs.io/docs/en/configuration#whats-your-use-case)

**webpack.config.js**

```js
...
module: {
  rules: [
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules\/(?!(goober)\/).*/, // we have to include goober
      loader: "babel-loader",
    },
  ],
},
...
```

I hope this can help in the meantime

**Comment by cristianbote** [comment]
Oh, maybe I should've been clearer 😅  but the idea is not to offer out of the box support for IE11. The size increase it's not justified. So what needs to happen is to update the browser support section to reflect that IE11 is not supported.

**Comment by itsabdessalam** [comment]
> Oh, maybe I should've been clearer 😅 but the idea is not to offer out of the box support for IE11. The size increase it's not justified. So what needs to happen is to update the browser support section to reflect that IE11 is not supported.

Totally agree with you! That's why I suggested the solution mentioned above for those who want to have IE11 support on their side

**Comment by cristianbote** [comment]
Totally @itsabdessalam! Good call.
