### ISSUE TITLE
Question about the indexOf in update

### ISSUE THREAD

**Issue by zhaoyao91** [cristianbote/goober#280]
see the [code](https://github.com/cristianbote/goober/blob/master/src/core/update.js#L20)

```
/**
 * Updates the target and keeps a local cache
 * @param {String} css
 * @param {Object} sheet
 * @param {Boolean} append
 */
export let update = (css, sheet, append) => {
    sheet.data.indexOf(css) == -1 && (sheet.data = append ? css + sheet.data : sheet.data + css);
};
```

There may be some problems

- when the sheet grows big, would it hurt performance cause indexOf may have a complexity of O(n*m)
- there may be wrong case for such a test, for example, if I already have a style `.a .b {color: blue}`, then want to add a style `.b {color: blue}`, as the new style is a substring of a, it won't be inserted.

**Comment by cristianbote** [comment]
Indeed for a large style sheet `indexOf` could be an issue, but I fail to see an implementation that would not have this issue 🤔 . Oh actually I think there might be one, via CSSOM. And it'll go something like this:

```js
// Let's assume we have a rule object shape, defined as an array, that has the selector, value and the whole rule.
const rule = ['.selector', 'property: value;', '.selector { property: value; }'];
// Getting the sheet instance
const sheet = document.getElementById('_goober').sheet;
// The CSSOM rules map
const rules = sheet.rules;

for (const key in rules) {
  const value = rules[key];

  // If the current rule selector matches the rule selector
  // we can mutate the current rule cssText and break the loop.
  if (value.selector === rule[0]) {
    value.cssText = rule[2];
    break;
  }
}
```

Now for the second issue, due to the way one needs to define the styles either via `css` or `styled`, I don't think there is a chance for that conflict to happen, since the `.b` selector and rule are tightly coupled based on the contents. So if `.b` changes the selector will change as well and so will the rule so they won't match anymore.
