### ISSUE TITLE
What's the catch? ;)

### ISSUE THREAD

**Issue by mikestopcontinues** [cristianbote/goober#292]
Hey @cristianbote, this project is damn awesome. 

I'm interested in converting a pretty large codebase, and I'm trying to figure out if there might be a hidden catch. I've read though the API and the comparison, but I'm flabbergasted you can keep everything with at 8% the size of styled-components.

I see that goober-autoprefixer adds 0.5k back in, which is _very reasonable_. But what else? Does the performance suffer in any way? I haven't been able to find a comparison on that front. Browser support? What accounts for the size difference?

Thanks!

**Comment by cristianbote** [comment]
Hey @mikestopcontinues!

Thanks for opening this issue with a valid question! 😄 

One thing that is certain is that you won't be suffering from performance degradation, neither on the server nor on the client. That is a certainty. You can peak at the benchmark folder to get a thorough look inside.

What you will be not getting with `goober` is the developer experience that the teams behind styled-components and emotion have thought of. With `goober` you can add a `.displayName` for each `styled` component but that's mostly it in terms of debugging.
One important thing that allowed `goober` to be really small is that I've come-up with a regex parser to parse out the tagged templates, that is really small and powerful. `styled-components` and `emotion` both use the same parser, as in stylis. Which is as well such a great project! At some point I even ran the `goober` css parsers on top of stylis tests, to make sure I'm implementing the right thing, and they pass. There's one small bug inside the parser right now, which is this one #173.

I'm really obsessed about the size. I've cut corners, sacrifice APIs only to keep `goober` under 1kB. That's why I launched [The Great Shave Off](https://goober.rocks/the-great-shave-off) campaign as well.

So, to conclude this, I've used `goober` across everywhere and I've been enjoying it so much! That's why I created it. I've seen it used on large projects, or small. At some point I even replaces the `react-native`'s `StyleSheet` with `goober` and everything worked great! 😄 

Hopefully this answered most of your questions about `goober`. Let me know if I can do a better job at answering it.

**Comment by mikestopcontinues** [comment]
@cristianbote Awesome! Thank you very much for the detailed response. I definitely switch over sometime within the next month, and when I do, I'll make a contribution via opencollective. Thanks again!

**Comment by alan-ws** [comment]
> Hey @mikestopcontinues!
> 
> Thanks for opening this issue with a valid question! smile
> 
> One thing that is certain is that you won't be suffering from performance degradation, neither on the server nor on the client. That is a certainty. You can peak at the benchmark folder to get a thorough look inside.
> 
> What you will be not getting with `goober` is the developer experience that the teams behind styled-components and emotion have thought of. With `goober` you can add a `.displayName` for each `styled` component but that's mostly it in terms of debugging. One important thing that allowed `goober` to be really small is that I've come-up with a regex parser to parse out the tagged templates, that is really small and powerful. `styled-components` and `emotion` both use the same parser, as in stylis. Which is as well such a great project! At some point I even ran the `goober` css parsers on top of stylis tests, to make sure I'm implementing the right thing, and they pass. There's one small bug inside the parser right now, which is this one #173.
> 
> I'm really obsessed about the size. I've cut corners, sacrifice APIs only to keep `goober` under 1kB. That's why I launched [The Great Shave Off](https://goober.rocks/the-great-shave-off) campaign as well.
> 
> So, to conclude this, I've used `goober` across everywhere and I've been enjoying it so much! That's why I created it. I've seen it used on large projects, or small. At some point I even replaces the `react-native`'s `StyleSheet` with `goober` and everything worked great! smile
> 
> Hopefully this answered most of your questions about `goober`. Let me know if I can do a better job at answering it.

Hey @cristianbote - would you be able to show me how you used goober with react-native. I am looking to unify a codebase and would like to use goober only for both react and react-native. I'd likely fork goober and implement the approach if I need to, unless it can work without changing much of the goober codebase
