### ISSUE TITLE
Improve development docs?

### ISSUE THREAD

**Issue by vfonic** [cristianbote/goober#300]
I wanted to try to shave off some of the bytes of the package, but I hit an issue trying to setup the package for local development.

Here are some of the issues I've encountered:

1. There's no documentation on what needs to be run and how/when in order to run tests locally
2. I cloned the repo and ran `npm i` followed by `npm run test`.
  This failed because it seems like I need to run `npm i` several times in several directories. To figure out which directories to run `npm i` for, I needed to manually check in the `package.json`, which folders were `cd`-ed into. Is there a better way that I'm not aware  of?
3. `docs` folder contains both `package-lock.json` and `yarn.lock`. This seems like one is not used or outdated.
4. `macro` folder has no lock files (same as the two packages in `packages` folder).
  I'm not an expert in npm package development and these things make it really hard to figure out the initial steps.
5. All of the `package.json` files declare `ISC` license.

**Comment by cristianbote** [comment]
Hi @vfonic!

So sorry, for my late response, for some reason got really sidetracked.

In a nutshell, I believe you are right, the development docs could be improved a lot. Now, let me address each point you made:

1. Indeed. Usually a `npm run test` should be enough. And `npm run test` can't run without `npm install`.
2. Correct again! I think this is the source of most tests commands not working and need a manual `npm i`.
3. Yup, I think the `package-lock` was my wrong doing. The initial `docs` are built with `yarn`.
4. `macro` has no dependencies, but rather `peerDependencies` so I guess there's no need for a `package-lock` since you are not installing dependencies.
5. Is `ISC` problematic? I selected `ISC` because is less verbose and it's the same as `MIT`.

Now, the best part of all of the above is that they can totally and completely be improved by anyone. So, if you can, I would love some help with the above. 🙏

**Comment by vfonic** [comment]
Thanks for the detailed response!

I'm on my phone so just a quick note for 5: the actual license in the repo in LICENSE file is MIT. that's the confusion I'm talking about here. It seems like the repo claims one license, while the package.json claims the other.

**Comment by cristianbote** [comment]
I believe this got solved meanwhile. Thanks @vfonic!
