### ISSUE TITLE
Are goober compatible and does it work well with remix.run?

### ISSUE THREAD

**Issue by dougg0k** [cristianbote/goober#410]
the title is the question.

https://remix.run/

**Comment by cristianbote** [comment]
Heya @dougg0k!

That's a fair question and when remix launched I looked into it and bumped into this section in their readme https://remix.run/docs/en/v1/guides/styling#css-in-js-libraries I followed the instructions there and it worked.

But I think what the team states there is quite true and makes total sense for remix so in order to make sure remix works fine I would follow their recommendation and not use css-in-js with remix. Let me know if you need more info on this or you run into issues.

**Comment by dougg0k** [comment]
Hey @cristianbote

Nah, that's enough, thanks.
