### ISSUE TITLE
createGlobalStyles only renders the last defined @font-face

### ISSUE THREAD

**Issue by nairdua** [cristianbote/goober#440]
Sandbox: https://codesandbox.io/s/goober-global-styles-fonts-vwjy82?file=/src/index.tsx
It appears that if you define multiple font-faces in createGlobalStyles, the last one defined will be the one rendered. I'm not sure if this is related to #102.

Thanks!

**Comment by cristianbote** [comment]
Hey @nairdua thanks for opening this issue!

Yup indeed, since the inner parser of goober basically translates the given styles into an internal tree-shape(AST) and that shape is basically an object, duplicate keys are basically overwritten by the latest read value. It's something that I wanna tackle in the next iteration. I'll keep this updated when it's ready.

Have a great one!

**Comment by nairdua** [comment]
Thanks for the response @cristianbote! As a workaround should I use `glob` or some other method to define the `@font-faces`?

**Comment by cristianbote** [comment]
I believe you could rely on it yes. Something like this:

```jsx
import RobotoRegularWoff from "../public/fonts/roboto-v29-latin-regular.woff";
import RobotoMediumWoff from "../public/fonts/roboto-v29-latin-500.woff";

const FontFace = ({ name, path }) => {
  glob`
    @font-face {
      font-family: '${name}';
      font-style: normal;
      font-weight: 400;
      src: url(${path}) format('woff');
    }
  `;
  return null;
};

function App() {
  return (
    <>
      <FontFace name="Roboto" url={RobotoRegularWoff} />
      <FontFace name="Roboto" url={RobotoMediumWoff} />
    </>
  );
}
```

Just heads-up I have not tested this yet, but should work.

**Comment by nairdua** [comment]
Thanks for the tip, I think we can close this issue.
